spring.application.name=lms

spring.datasource.url=jdbc:mysql://urntable.proxy.rlwy.net:52399/railway
spring.datasource.username=root
spring.datasource.password=EqTnovidrknUMJRldsNRcRioxdFNKYht

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration